### ISSUE TITLE
Read infiles: unexpected keyword argument 'package_keys'

### ISSUE THREAD

**Issue by mauritsvanrees** [mxstack/mxdev#12]
I wanted to try out the latest changes. I did that in `plone.scale` with this change in [`tox.ini`](https://github.com/plone/plone.scale/blob/master/tox.ini):

```
 [testenv:plone60-py{37,38,39,310}]
 commands_pre =
-    pip install mxdev
+    pip install git+https://github.com/bluedynamics/mxdev.git@main
     mxdev -c sources-60.ini
     pip install --use-deprecated legacy-resolver -rrequirements-60-mxdev.txt
```

I than ran the Plone 6 Python 3.8 env (avoiding issue #10 on Py 3.9+) and this failed:

```
$ tox -e plone60-py38
plone60-py38 create: /Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38
plone60-py38 run-test-pre: PYTHONHASHSEED='2339498946'
plone60-py38 run-test-pre: commands[0] | pip install git+https://github.com/bluedynamics/mxdev.git@main
Collecting git+https://github.com/bluedynamics/mxdev.git@main
  Cloning https://github.com/bluedynamics/mxdev.git (to revision main) to /private/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/pip-req-build-o7neug69
  Running command git clone --filter=blob:none --quiet https://github.com/bluedynamics/mxdev.git /private/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/pip-req-build-o7neug69
  Resolved https://github.com/bluedynamics/mxdev.git to commit 1d2d7aa0a7409120437c1d8e299690f31d0748d4
  Preparing metadata (setup.py) ... done
Requirement already satisfied: setuptools in ./.tox/plone60-py38/lib/python3.8/site-packages (from mxdev==2.1.0.dev0) (62.0.0)
Collecting libvcs>=0.10.1
  Using cached libvcs-0.11.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: mxdev
  Building wheel for mxdev (setup.py) ... done
  Created wheel for mxdev: filename=mxdev-2.1.0.dev0-py3-none-any.whl size=10013 sha256=971e2731fbb323b9324e1fce046824f7c0de1cea4bb4f405ba6d0c837e50c4a3
  Stored in directory: /private/var/folders/26/1plvhxbs6yx7g_82v2xdxc500000gn/T/pip-ephem-wheel-cache-ckwnrjvt/wheels/7f/2f/3a/540b397dc603c9eee3e0e25feaad96b9abbb0840cd2cfe59a9
Successfully built mxdev
Installing collected packages: libvcs, mxdev
Successfully installed libvcs-0.11.1 mxdev-2.1.0.dev0
plone60-py38 run-test-pre: commands[1] | mxdev -c sources-60.ini
###############################################################################
# Load configuration
Can not parse override: 
###############################################################################
# Read infiles
Read [r]: requirements-60.txt
Traceback (most recent call last):
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/bin/mxdev", line 8, in <module>
    sys.exit(main())
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/lib/python3.8/site-packages/mxdev.py", line 416, in main
    read(state)
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/lib/python3.8/site-packages/mxdev.py", line 259, in read
    process_io(
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/lib/python3.8/site-packages/mxdev.py", line 233, in process_io
    new_requirements, new_constraints = process_line(
  File "/Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/lib/python3.8/site-packages/mxdev.py", line 192, in process_line
    return read(
TypeError: read() got an unexpected keyword argument 'package_keys'
ERROR: InvocationError for command /Users/maurits/community/plone-coredev/6.0/src/plone.scale/.tox/plone60-py38/bin/mxdev -c sources-60.ini (exited with code 1)
_________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________
ERROR:   plone60-py38: commands failed
```

Indeed the `read` method no longer accepts this keyword argument since PR #8.

**Comment by jensens** [comment]
@mauritsvanrees OT here, but `--use-deprecated legacy-resolver` is no longer needed (given a recent pip).

**Comment by rnixx** [comment]
Yes, my changes broke it. I'll have a look
